// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
config({ path: '.env' });

import { defineConfig } from 'prisma/config';

const url = process.env.DATABASE_URL;
if (!url) throw new Error('DATABASE_URL not found in backend/.env');

export default defineConfig({
  schema: 'prisma/schema.prisma',
  datasource: { url },
});
